/*
 * This file is generated by jOOQ.
 */
package com.vaadin.starter.beveragebuddy.backend.jooq.indexes


import com.vaadin.starter.beveragebuddy.backend.jooq.tables.Category
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.FlywaySchemaHistory
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.Review

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY_S_IDX: Index = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS), false)
val IDX_CATEGORY_NAME: Index = Internal.createIndex(DSL.name("IDX_CATEGORY_NAME"), Category.CATEGORY, arrayOf(Category.CATEGORY.NAME), true)
val IDX_REVIEW_NAME: Index = Internal.createIndex(DSL.name("IDX_REVIEW_NAME"), Review.REVIEW, arrayOf(Review.REVIEW.NAME), false)
