/*
 * This file is generated by jOOQ.
 */
package com.vaadin.starter.beveragebuddy.backend.jooq.tables.pojos


import com.vaadin.starter.beveragebuddy.backend.CategoryDaoExt
import com.vaadin.starter.beveragebuddy.backend.dao
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.daos.CategoryDao
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.records.CategoryRecord
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.references.CATEGORY
import com.vaadin.starter.beveragebuddy.backend.simplejooq.ActivePojo
import com.vaadin.starter.beveragebuddy.backend.simplejooq.currentConfiguration
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size
import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Category(
    var id: Long? = null,
    @get:Size(max = 200)
    @get:NotBlank
    var name: String? = null
): Serializable, ActivePojo<CategoryRecord, Category, Long> {

    override fun dao(cfg: Configuration?): DAOImpl<CategoryRecord, Category, Long> =
        CategoryDaoExt(cfg)
}
