/*
 * This file is generated by jOOQ.
 */
package com.vaadin.starter.beveragebuddy.backend.jooq.tables.pojos


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class FlywaySchemaHistory(
    @get:NotNull
    var installedRank: Int? = null,
    @get:Size(max = 50)
    var version: String? = null,
    @get:NotNull
    @get:Size(max = 200)
    var description: String? = null,
    @get:NotNull
    @get:Size(max = 20)
    var type: String? = null,
    @get:NotNull
    @get:Size(max = 1000)
    var script: String? = null,
    var checksum: Int? = null,
    @get:NotNull
    @get:Size(max = 100)
    var installedBy: String? = null,
    var installedOn: LocalDateTime? = null,
    @get:NotNull
    var executionTime: Int? = null,
    @get:NotNull
    var success: Boolean? = null
): Serializable {
}
