/*
 * This file is generated by jOOQ.
 */
package com.vaadin.starter.beveragebuddy.backend.jooq.tables.pojos


import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.time.LocalDate


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Review(
    var id: Long? = null,
    @get:NotNull
    @get:Size(max = 200)
    var name: String? = null,
    @get:NotNull
    var score: Byte? = null,
    @get:NotNull
    var date: LocalDate? = null,
    var category: Long? = null,
    @get:NotNull
    var count: Byte? = null
): Serializable {


    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Review = other as Review
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        if (this.score == null) {
            if (o.score != null)
                return false
        }
        else if (this.score != o.score)
            return false
        if (this.date == null) {
            if (o.date != null)
                return false
        }
        else if (this.date != o.date)
            return false
        if (this.category == null) {
            if (o.category != null)
                return false
        }
        else if (this.category != o.category)
            return false
        if (this.count == null) {
            if (o.count != null)
                return false
        }
        else if (this.count != o.count)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        result = prime * result + (if (this.score == null) 0 else this.score.hashCode())
        result = prime * result + (if (this.date == null) 0 else this.date.hashCode())
        result = prime * result + (if (this.category == null) 0 else this.category.hashCode())
        result = prime * result + (if (this.count == null) 0 else this.count.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Review (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(score)
        sb.append(", ").append(date)
        sb.append(", ").append(category)
        sb.append(", ").append(count)

        sb.append(")")
        return sb.toString()
    }
}
