/*
 * This file is generated by jOOQ.
 */
package com.vaadin.starter.beveragebuddy.backend.jooq.tables.pojos


import com.vaadin.starter.beveragebuddy.backend.jooq.tables.daos.ReviewDao
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.records.ReviewRecord
import com.vaadin.starter.beveragebuddy.backend.simplejooq.ActivePojo
import com.vaadin.starter.beveragebuddy.backend.simplejooq.currentConfiguration
import jakarta.validation.constraints.*
import org.jooq.Configuration
import org.jooq.impl.DAOImpl

import java.io.Serializable
import java.time.LocalDate


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Review(
    var id: Long? = null,
    @get:Size(min = 3, max = 200)
    @get:NotBlank
    var name: String? = null,
    @get:NotNull
    @get:Min(1)
    @get:Max(5)
    var score: Byte? = null,
    @get:NotNull
    @get:PastOrPresent
    var date: LocalDate? = null,
    @get:NotNull
    var category: Long? = null,
    @get:NotNull
    @get:Min(1)
    @get:Max(99)
    var count: Byte? = null
): Serializable, ActivePojo<ReviewRecord, Review, Long> {

    override fun dao(cfg: Configuration?): DAOImpl<ReviewRecord, Review, Long> = ReviewDao(cfg)
}
