/*
 * This file is generated by jOOQ.
 */
package com.vaadin.starter.beveragebuddy.backend.jooq.tables.references


import com.vaadin.starter.beveragebuddy.backend.jooq.tables.Category
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.FlywaySchemaHistory
import com.vaadin.starter.beveragebuddy.backend.jooq.tables.Review



/**
 * The table <code>PUBLIC.CATEGORY</code>.
 */
val CATEGORY: Category = Category.CATEGORY

/**
 * The table <code>PUBLIC.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>PUBLIC.REVIEW</code>.
 */
val REVIEW: Review = Review.REVIEW
